version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

services:

### nginx ###########################################
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${LOCAL_PATH}:${DOCKER_PATH}
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./certbot/conf/:/etc/nginx/ssl
    depends_on:
      - php
    networks:
      backend:
        aliases:
          - website-pm-sg.test
          - unified-portal.test
    restart: "no"

### php ###########################################
  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ./php/php8.1.ini:/usr/local/etc/php/php.ini
      - ${LOCAL_PATH}:${DOCKER_PATH}
    ports:
      - "9000:9000"
    networks:
      - backend
    restart: "no"

### mysql ###########################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: mysql
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ${LOCAL_DATA_PATH}/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend
    restart: "no"

  certbot:
      container_name: certbot
      image: certbot/certbot:latest
      command: certonly --webroot --webroot-path=/var/www/html/certbot --email dzung1nguyen@gmail.com --agree-tos --no-eff-email -d 7broscore.com -d www.7broscore.com
      volumes:
          - ./certbot/conf:/etc/letsencrypt
          - ./certbot/logs:/var/log/letsencrypt
          - ./certbot/data:/var/www/html/certbot
      networks:
        - backend

### PostgreSQL ###########################################
  postgres:
    build:
      context: ./postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    container_name: postgres
    volumes:
      - ${LOCAL_DATA_PATH}/postgres:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    restart: ${RESTART_POSTGRES}

# ### redis ###########################################
#   redis:
#     build:
#       context: ./redis
#       args:
#         - REDIS_VERSION=${REDIS_VERSION}
#     volumes:
#       - ${LOCAL_DATA_PATH}/redis:/data
#     container_name: redis
#     ports:
#       - "${REDIS_PORT}:6379"
#     networks:
#       - backend
#     restart: ${RESTART_REDIS}

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    networks:
      - backend
